val studyLocations = arrayOf(
        "Massachusetts Institute of Technology (MIT)",
        "Stanford University",
        "Harvard University",
        "California Institute of Technology (Caltech)",
        "University of Oxford",
        "ETH Zurich (Swiss Federal Institute of Technology)",
        "University of Cambridge",
        "Imperial College London",
        "University of Chicago",
        "UCL (University College London)",
        "National University of Singapore (NUS)",
        "Princeton University",
        "Nanyang Technological University, Singapore (NTU)",
        "Ecole Polytechnique Fédérale de Lausanne (EPFL)",
        "Tsinghua University",
        "University of Pennsylvania",
        "Yale University",
        "Cornell University",
        "Columbia University",
        "University of Edinburgh",
        "University of Michigan-Ann Arbor",
        "University of Hong Kong (UKU)",
        "Peking University",
        "University of Tokyo",
        "Johns Hopkins University",
        "University of Toronto",
        "Hong Kong University of Science and Technology (HKUST)",
        "University of Manchester",
        "Northwestern University",
        "University of California, Berkeley (UCB)",
        "Australian National University",
        "King's College London",
        "McGill University",
        "Fudan University",
        "New York University (NYU)",
        "University of California, Los Angeles (UCLA)",
        "Seoul National University",
        "Kyoto University",
        "KAIST - Korea Advanced Institute of Science & Technology",
        "University of Sydney",
        "University of Melbourne",
        "Duke University",
        "Chinese University of Hong Kong (CUHK)",
        "University of New South Wales (UNSW Sydney)",
        "University of British Columbia",
        "University of Queensland",
        "Shanghai Jiao Tong University",
        "City University of Hong Kong",
        "London School of Economics and Political Science (LSE)",
        "Technical University of Munich",
        "Carnegie Mellon University",
        "Universite PSL",
        "Zhejiang University",
        "University of California, San Diego (UCSD)",
        "Monash University",
        "Tokyo Institute of Technology",
        "Delft University of Technology",
        "University of Bristol",
        "Universiti Malaya (UM)",
        "Brown University",
        "University of Amsterdam",
        "University of Warwick",
        "Ludwig-Maximilians-Universität München",
        "Ruprecht-Karls-Universitat Heidelberg",
        "University of Wisconsin-Madison",
        "National Taiwan University (NTU)",
        "Universidad de Buenos Aires (UBA)",
        "Ecole Polytechnique",
        "Korea University",
        "University of Zurich",
        "University of Texas at Austin",
        "Osaka University",
        "University of Washington",
        "Lomonosov Moscow State University",
        "Hong Kong Polytechnic University",
        "University of Copenhagen",
        "Pohang University of Science and Technology (POSTECH)",
        "University of Glasgow",
        "Tohoku University",
        "Georgia Institute of Technology",
        "University of Auckland",
        "University of Illinois at Urbana-Champaign",
        "Sorbonne University",
        "KU Leuven",
        "Durham University",
        "Yonsei University",
        "University of Birmingham",
        "Sungkyunkwan University (SKKU)",
        "Rice University",
        "University of Southampton",
        "University of Leeds",
        "University of Western Australia",
        "University of Sheffield",
        "University of Science and Technology of China",
        "University of North Carolina, Chapel Hill",
        "University of St Andrews",
        "Lund University",
        "KTH Royal Institute of Technology",
        "University of Nottingham",
        "Universidad Nacional Autónoma de México (UNAM)"
)